# Generated by Django 2.2.4 on 2019-09-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', "Laptops/PC's"), ('SW', 'Consumer Electronics'), ('OW', 'Smart Vehicles')], max_length=2),
        ),
    ]
